Equality

```{r}
"Rchitect" != "rchitect"
TRUE == FALSE
-6 * 14 != 17 - 101
TRUE == 1

-6 * 5 + 2 >= -10 + 1
"raining" <= "raining dogs"
TRUE < FALSE

```

compare vectors

```{r}
linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,9,16,5,2,13,14)

linkedin > 15
facebook <= 5

linkedin > facebook
```
compare matrices

```{r}
views <- matrix(c(linkedin,facebook), nrow = 2, byrow = TRUE)
views

views == 13

views <= 14
```
& and |

```{r}
linkedin
last <- tail(linkedin,1)

last > 5 | last < 10
last > 15 & last <= 20

linkedin > 10 & facebook < 10
linkedin >= 12 | facebook >= 12
```
The if statement

```{r}
medium <- "Linkedin"
num_views <- 14

if(medium == "Linkedin"){
  print("showing Linkedin information")
} else {
  print("unknown medium")
}

if(num_views > 15){
  print(("You are popular!"))
} else if (num_views <= 15 & num_views > 10) {
  print("Your number of views is average")
} else {
  print("try to be more visible")
}
  
```


```{r}
result <- ""
number <- 6

if (number <10){
  if(number < 5){
    result <- "extra small"
  }
} else if (number <100){
  result <- "medium"
} else {
  result <- "large"
}
```
print(result)




write a while loop

```{r}
speed <- 64

while (speed < 30){
  print("slow down")
  speed <- speed - 7
}

speed
```
```{r}
while (speed > 30) {
  print(paste("Your speed is",speed))
  if(speed>=48){
    print("slow down big time!")
    speed <- speed - 11
  } else {
    print("slow down!")
    speed <- speed - 6
  }
}

speed
```
stop the while loop: break

```{r}

speed <- 88

while (speed > 30) {
  print(paste("Your speed is",speed))
  
  if (speed > 80){
    break
  }
  if(speed >48){
    print("Slow down big time!")
    speed <- speed -11
  } else {
    print("Slow down!")
    speed <- speed - 6
  }
}
```

Build a while loop from scratch

```{r}
i <- 1

while (i <=10){
  print(3*i)
  if((i*3) %% 8 == 0){
    break
  }
  i <- i + 1
}
```

