Arithmetic with R

```{r}
5+5-3
10-2
3+5
(5+5)/2
28%%6

```

Variable assignment

```{r}
x <- 10
x

y <- 9

x+y
result <- x-y
result


```

Basics data types in R

```{r}

my_numeric <- 423

my_character <- "universe"

my_logical <- FALSE

class(my_numeric)
class(my_character)
class(my_logical)

```
Create a vector

```{r}

numeric_vector <- c(1,10,49)
numeric_vector

character_vector <- c("a","b","c")

boolean_vector <- c(TRUE,FALSE,TRUE)

character_vector
boolean_vector


poker_vector <- c(140,50,-20,-120)
roulette_vector <- c(-24,-50,10,350,10)


poker_vector

```

numeric_vector = c(1,10,49)
numeric_vector

Naming a vector

```{r}
names(poker_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
poker_vector

names(roulette_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
roulette_vector

days <- c("Monday","Tuesday","Wednesday","Thursday","Friday")

names(poker_vector) <- days
poker_vector

```

selection by comparison

```{r}

age <- 17

age >= 18

selection_vector <- poker_vector > 0
selection_vector

poker_winning_days <- poker_vector[selection_vector]
poker_winning_days
```
Calculating

```{r}
x_vector <- c(4,7,9)
y_vector <- c(12,45,78)

result_vector <- y_vector + x_vector
result_vector

```

```{r}
sex_vector <- c("Male","Female","Female","Male",Male")
factor_sex_vector <-factor_sex_vector)
factor_sex_vector

```

```{r}
temperature_vector <- c("High","Low","High","Low","Medium")
factor_temperature_vector <- factor(temperature_vector,order=True,levels=c("Low,"Medium","High"))

```


Matrices

```{r}
matrix(1:9, byrow = TRUE, nrow=3)
```
Analyze matrices

```{r}

new_hope <- c(460.998,314.4)
empire_strikes <- c(290.475,247.900)
return_jedi <- c(309.306,165.8)

box_office  <- c(new_hope, empire_strikes, return_jedi)
box_office

stars_wars_matrix <- matrix(box_office, byrow = TRUE, nrow=3)
stars_wars_matrix
```
```{r}
region <- c("US", "non-US")
titles <- c("A new hope", "The empire strikes back", "Return of the Jedi")

colnames(stars_wars_matrix) <- region
rownames(stars_wars_matrix) <- titles
stars_wars_matrix

```

rowSums

```{r}
rowSums(stars_wars_matrix)
colSums(stars_wars_matrix)
```
cbind and rbind


```{r}
total_revenue_by_title <- rowSums(stars_wars_matrix)
total_revenue_by_region <- colSums(stars_wars_matrix)
                                   
total <- cbind(stars_wars_matrix,total_revenue_by_title)
total <- rbind(total, total_revenue_by_region)
total


```
Selection of matrix elements

```{r}
stars_wars_matrix

stars_wars_matrix[1,2]
stars_wars_matrix[1:2,2]

stars_wars_matrix[c(1,3),1]
stars_wars_matrix[c(1,3),]

```
Arithmetic with matrices

```{r}

mean <- stars_wars_matrix/5
mean * 2

```
Factor

```{r}
sex_vector <- c("Male","Female","Female","Male","Male")
factor_sex_vector <- factor(sex_vector)
factor_sex_vector

```
```{r}
temperature_vector <- c("High","Low","High","Low","Medium")
factor_temprature_vector <- factor(temperature_vector, order=TRUE, levels=c("Low","Medium","High"))
factor_temprature_vector
```
Factor levels

```{r}
survey_vector <- c("M","F","F","M","M")
factor_survey_vector <- factor(survey_vector)
factor_survey_vector
levels(factor_survey_vector) <- c("Female","Male")
```

Summary

```{r}
summary(factor_survey_vector)
```
Ordered factors

```{r}
male <- factor_survey_vector[1]
female <- factor_survey_vector[2]

male > female


speed_vector <- c ("medium","slow","slow","medium","fast")
factor_speed_vector<- factor(speed_vector)
factor_speed_vector<- factor(speed_vector, ordered = TRUE, levels=c("slow","medium","fast"))

speed_1 <- factor_speed_vector[2]
speed_5 <- factor_speed_vector[5]
speed_1 > speed_5
speed_5 > speed_1


```





